"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {Database,FlaskConical,Play,Check,Layers,Clock,Plus,Activity,Wallet,ShieldCheck} from "lucide-react";
import {useWorkspace,Badge,Notice} from "./workspace";
import {num,pct,day} from "@/lib/format";
export default function Dashboard(){
  const {datasets,strategies,runs,busy,execute}=useWorkspace();const router=useRouter();const [error,setError]=useState("");
  const dataset=datasets.find(d=>d.id==="synthetic-seed-33")||datasets[0];const strategy=strategies.find(s=>s.id==="strategy-demo")||strategies[0];const completed=runs.filter(r=>r.status==="completed");const latest=completed[0];
  async function run(){if(!strategy)return;try{setError("");const r=await execute(strategy);router.push(`/results/?run=${r.id}`);}catch(e){setError(e instanceof Error?e.message:String(e));}}
  return <><div className="page-heading"><div><div className="eyebrow">RESEARCH OVERVIEW</div><h1>Your workspace</h1><p>Turn on-chain hypotheses into reproducible experiments.</p></div><Link className="button primary" href="/lab/"><Plus size={17}/>New experiment</Link></div>
    {error&&<Notice error>{error}</Notice>}
    <div className="stat-grid"><div className="stat"><span><Database size={16}/>Research datasets</span><strong>{datasets.length.toString().padStart(2,"0")}</strong><small>{datasets.filter(d=>d.quality.performance_ready).length} ready for evaluation</small></div><div className="stat"><span><Wallet size={16}/>Observed wallets</span><strong>{num(dataset?.wallets.length,0)}</strong><small>Within the selected demo universe</small></div><div className="stat"><span><Layers size={16}/>Market observations</span><strong>{num(dataset?.quality.market_observations,0)}</strong><small>{dataset?.resolution_seconds/60}-minute historical snapshots</small></div><div className="stat"><span><FlaskConical size={16}/>Completed experiments</span><strong>{completed.length.toString().padStart(2,"0")}</strong><small>{strategies.length} saved research {strategies.length===1?"project":"projects"}</small></div></div>
    <div className="dashboard-grid"><section className="panel research-card"><div className="panel-heading"><h2>Featured research</h2><span className="small-label">STRATEGY 001</span></div><div className="research-title"><div className="icon-box"><FlaskConical size={24}/></div><div><h3>Smart Money Accumulation</h3><div className="tag-row"><Badge kind={dataset?.kind||"SYNTHETIC"}/><span className="tag">Long only</span><span className="tag">Event driven</span></div></div></div><p className="hypothesis">When multiple previously profitable wallets buy the same token, does the signal survive trading costs?</p><div className="research-pipeline"><div><span>01</span><b>Observe</b><small>Past wallet performance</small></div><div><span>02</span><b>Test</b><small>Chronological execution</small></div><div><span>03</span><b>Validate</b><small>Unseen time period</small></div></div><div className="card-action"><span><Clock size={15}/>14 days · 4 tokens · Seed 33</span><button className="button primary" disabled={busy||!strategy} onClick={run}><Play size={15}/>Run reference experiment</button></div></section>
    <section className="panel"><div className="panel-heading"><h2>Dataset integrity</h2><ShieldCheck size={19} className="mint"/></div>{dataset&&<><div className="quality-score"><strong>{num(dataset.quality.price_coverage_pct,0)}<span>%</span></strong><div>Historical price coverage<small>{dataset.quality.performance_ready?"Required market fields present":"Performance calculations blocked"}</small></div></div><div className="quality-list">{[["Historical prices",`${num(dataset.quality.price_coverage_pct,0)}%`],["Historical liquidity",`${num(dataset.quality.liquidity_coverage_pct,0)}%`],["Missing market bars",dataset.quality.missing_bars],["Event identity","Deduplicated"]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{value}</b></div>)}</div><div className="mini-notice"><Badge kind={dataset.kind}/><span>{dataset.kind==="SYNTHETIC"?"Simulation data. Not actual Solana returns.":"Inspect provenance before interpreting results."}</span></div></>}</section></div>
    <section className="panel"><div className="panel-heading"><div><h2>Research projects</h2><p>Saved hypotheses and strategy configurations.</p></div><Link className="text-link" href="/lab/">Open strategy lab</Link></div><div className="project-list">{strategies.slice(0,4).map(s=><Link key={s.id} href={`/lab/?strategy=${s.id}`} className="project-row"><div className="icon-box small"><FlaskConical size={18}/></div><div className="grow"><b>{s.name}</b><small>{s.config.min_wallet_count} wallets · {s.config.accumulation_minutes}m accumulation · {s.config.holding_minutes}m hold</small></div><Badge kind={datasets.find(d=>d.id===s.dataset_id)?.kind||"SYNTHETIC"}/><span className="tag">{num(s.config.train_fraction*100,0)} / {num((1-s.config.train_fraction)*100,0)} split</span></Link>)}</div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Recent experiments</h2><p>Independent runs, exact configurations, inspectable trades.</p></div><Activity size={18} className="subtle"/></div>{runs.length?<div className="table-wrap"><table><thead><tr><th>Experiment</th><th>Dataset</th><th>Status</th><th>OOS net return</th><th>Closed trades</th><th>Created</th></tr></thead><tbody>{runs.slice(0,6).map(r=><tr key={r.id}><td><Link className="text-link" href={`/results/?run=${r.id}`}>{r.config.name}</Link><small className="mono">{r.id.slice(-8)}</small></td><td><Badge kind={r.summary?.dataset_kind||datasets.find(d=>d.id===r.dataset_id)?.kind||"SYNTHETIC"}/></td><td><span className={`status ${r.status}`}>{r.status==="completed"&&<Check size={13}/>} {r.status}</span></td><td className={(r.summary?.out_of_sample.net_return_pct??0)<0?"negative":"positive"}>{pct(r.summary?.out_of_sample.net_return_pct)}</td><td>{r.summary?.out_of_sample.trade_count??"—"}</td><td className="subtle">{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<div className="inline-empty"><div className="icon-box"><Activity size={24}/></div><div><h3>Your first hypothesis is ready to test.</h3><p>Run the reference experiment to inspect returns, costs and every execution.</p></div></div>}</section>
    {latest&&<div className="notice neutral"><Check size={17}/><span>Latest completed run: out-of-sample net return <b>{pct(latest.summary?.out_of_sample.net_return_pct)}</b>. <Link href={`/results/?run=${latest.id}`}>Inspect the evidence</Link></span></div>}
    <div className="bottom-note"><Database size={15}/><span>Demo coverage: {dataset?`${day(dataset.start_ts)} – ${day(dataset.end_ts)}, 2026 (UTC)`:"No dataset"}. A successful backtest does not imply a profitable strategy.</span></div></>;
}
