"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {Play,Save,RotateCcw,Wallet,SlidersHorizontal,Coins,ShieldCheck,FlaskConical} from "lucide-react";
import {useWorkspace,Badge,Notice} from "./workspace";
import {saveStrategy} from "@/lib/api";
import type {Config} from "@/lib/types";
import {num,usd} from "@/lib/format";
type NumberKey={ [K in keyof Config]: Config[K] extends number ? K : never }[keyof Config];
const groups:{title:string;note:string;icon:typeof Wallet;fields:{key:NumberKey;label:string;min:number;max:number;step?:number;unit:string;hint?:string}[]}[]=[
  {title:"Signal & wallet eligibility",note:"All wallet scores use completed trades strictly before each signal.",icon:Wallet,fields:[
    {key:"min_wallet_count",label:"Minimum unique buyers",min:1,max:100,unit:"wallets"},
    {key:"accumulation_minutes",label:"Accumulation window",min:1,max:1440,unit:"min"},
    {key:"min_wallet_return_pct",label:"Prior wallet return",min:-100,max:10000,step:0.5,unit:"% minimum"},
    {key:"min_closed_trades",label:"Prior matched sales",min:1,max:10000,unit:"trades"},
    {key:"min_volume_usd",label:"Selected-wallet buy volume",min:0,max:1e12,step:100,unit:"USD minimum"},
    {key:"min_liquidity_usd",label:"Historical liquidity",min:0,max:1e12,step:1000,unit:"USD minimum"},
    {key:"min_token_age_hours",label:"Verified token age",min:0,max:1e7,unit:"hours",hint:"0 disables this filter"},
    {key:"min_momentum_pct",label:"Recent price momentum",min:-100,max:10000,step:0.1,unit:"% minimum",hint:"−100 disables this filter"},
    {key:"momentum_minutes",label:"Momentum lookback",min:1,max:1440,unit:"min"}]},
  {title:"Execution & risk",note:"Entries follow signals. Stop and target triggers fill on the next observed price.",icon:SlidersHorizontal,fields:[
    {key:"initial_capital_usd",label:"Initial capital per segment",min:1,max:1e10,step:100,unit:"USD"},
    {key:"position_size_usd",label:"Position budget",min:1,max:1e9,step:100,unit:"USD",hint:"Includes entry fees"},
    {key:"entry_delay_minutes",label:"Entry delay",min:0,max:1440,unit:"min"},
    {key:"holding_minutes",label:"Maximum holding period",min:1,max:10080,unit:"min"},
    {key:"take_profit_pct",label:"Take profit",min:.01,max:10000,step:.1,unit:"%"},
    {key:"stop_loss_pct",label:"Stop loss",min:.01,max:99.99,step:.1,unit:"%"},
    {key:"max_liquidity_participation_pct",label:"Liquidity participation cap",min:.001,max:10,step:.1,unit:"% per execution"}]},
  {title:"Trading costs",note:"Costs are applied on both entry and exit. No zero-cost assumption is hidden.",icon:Coins,fields:[
    {key:"fee_bps",label:"Trading fee",min:0,max:1000,step:1,unit:"bps / side"},
    {key:"slippage_bps",label:"Adverse slippage",min:0,max:1000,step:1,unit:"bps / side"},
    {key:"fixed_fee_usd",label:"Network & priority fee",min:0,max:1000,step:.01,unit:"USD / side"}]}];
export default function StrategyLab(){
  const {datasets,strategies,busy,progress,execute,refresh}=useWorkspace();const router=useRouter();
  const [c,setC]=useState<Config|null>(null),[datasetId,setDatasetId]=useState(""),[strategyId,setStrategyId]=useState<string|undefined>(),[message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("strategy");const s=strategies.find(s=>s.id===id)||strategies.find(s=>s.id==="strategy-demo")||strategies[0];if(s&&!c){const d=datasets.find(d=>d.id===s.dataset_id);setC({...s.config,wallet_ids:s.config.wallet_ids.length?s.config.wallet_ids:d?.wallets||[]});setDatasetId(s.dataset_id);if(id)setStrategyId(id);}},[strategies,datasets,c]);
  const d=datasets.find(x=>x.id===datasetId);if(!c)return <Notice>No research strategy is available. Seed the demo through the API.</Notice>;
  const config=c;const set=<K extends keyof Config>(key:K,value:Config[K])=>{setC({...config,[key]:value});setMessage("");};
  async function save(run=false){try{setError("");setSaving(true);const s=await saveStrategy(datasetId,config,strategyId);setStrategyId(s.id);await refresh();setMessage("Configuration saved.");if(run){const r=await execute(s);router.push(`/results/?run=${r.id}`);}}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}
  const walletWarning=config.wallet_ids.length<config.min_wallet_count;const disabled=busy||saving||!d?.quality.performance_ready||walletWarning;
  return <><div className="page-heading"><div><div className="eyebrow">HYPOTHESIS → FACTORS → EVIDENCE</div><h1>Strategy lab</h1><p>Define the experiment. Keep every assumption explicit.</p></div><span className="tag large"><FlaskConical size={16}/>Smart Money Accumulation</span></div>
    {error&&<Notice error>{error}</Notice>}{message&&<div className="notice success" role="status"><ShieldCheck size={17}/>{message}</div>}
    <form onSubmit={e=>{e.preventDefault();void save(true);}}><div className="lab-grid"><div className="lab-controls"><section className="panel"><div className="panel-heading"><h2>Research setup</h2><span className="section-number">01</span></div><div className="form-grid two"><label>Experiment name<input required maxLength={120} value={c.name} onChange={e=>set("name",e.target.value)}/></label><label>Historical dataset<select value={datasetId} onChange={e=>{setDatasetId(e.target.value);set("wallet_ids",datasets.find(d=>d.id===e.target.value)?.wallets||[]);setStrategyId(undefined);}}>{datasets.map(d=><option key={d.id} value={d.id}>{d.kind} · {d.name}</option>)}</select></label></div><label className="full-label">Hypothesis<textarea maxLength={4000} rows={3} value={c.hypothesis} onChange={e=>set("hypothesis",e.target.value)}/></label><div className="dataset-inline"><Badge kind={d?.kind||"SYNTHETIC"}/><span>{d?.tokens.length} tokens · {(d?.resolution_seconds||0)/60}-minute observations · {num(d?.quality.swap_events,0)} swaps</span></div></section>
    <section className="panel"><div className="panel-heading"><div><h2>Wallet universe</h2><p>{c.wallet_ids.length} selected · eligibility recalculated at every signal</p></div><button type="button" className="text-link" onClick={()=>set("wallet_ids",d?.wallets||[])}>Select all</button></div><div className="wallet-grid">{d?.wallets.map(w=><label className={`wallet-chip ${c.wallet_ids.includes(w)?"selected":""}`} key={w}><input type="checkbox" checked={c.wallet_ids.includes(w)} onChange={e=>set("wallet_ids",e.target.checked?[...c.wallet_ids,w]:c.wallet_ids.filter(x=>x!==w))}/><Wallet size={14}/><span title={w}>{w.startsWith("SYNTH")?w.replace("SYNTH_","Wallet "):w.slice(0,5)+"…"+w.slice(-4)}</span></label>)}</div>{walletWarning&&<Notice>Choose at least {c.min_wallet_count} wallets, or lower the minimum buyer count.</Notice>}</section>
    {groups.map((g,index)=><section className="panel" key={g.title}><div className="panel-heading"><div><h2><g.icon size={18}/>{g.title}</h2><p>{g.note}</p></div><span className="section-number">0{index+2}</span></div><div className="form-grid">{g.fields.map(f=><label key={f.key}>{f.label}<div className="number-control"><input required type="number" min={f.min} max={f.max} step={f.step&&f.min!==0?"any":f.step||1} value={c[f.key]} onChange={e=>set(f.key,e.target.value===""?0:Number(e.target.value))}/><span>{f.unit}</span></div>{f.hint&&<small>{f.hint}</small>}</label>)}</div></section>)}</div>
    <aside className="experiment-aside"><section className="panel sticky-panel"><div className="panel-heading"><h2>Validation protocol</h2><ShieldCheck size={19} className="mint"/></div><p className="body-small">Chronological holdout. Independent capital and positions in each period.</p><label className="full-label">Wallet-history warmup<div className="number-control"><input type="number" required min={1} max={720} value={c.warmup_hours} onChange={e=>set("warmup_hours",Number(e.target.value))}/><span>hours</span></div></label><div className="split-header"><span>In sample <b>{Math.round(c.train_fraction*100)}%</b></span><span>Out of sample <b>{Math.round((1-c.train_fraction)*100)}%</b></span></div><input aria-label="Training share" className="range" type="range" min={20} max={80} value={Math.round(c.train_fraction*100)} onChange={e=>set("train_fraction",Number(e.target.value)/100)}/><div className="split-legend"><i/>In sample <i/>Out of sample</div><div className="summary-lines"><div><span>Initial capital</span><b>{usd(c.initial_capital_usd)}</b></div><div><span>Position budget</span><b>{usd(c.position_size_usd)}</b></div><div><span>Fees + slippage</span><b>{num((c.fee_bps+c.slippage_bps)*2,0)} bps round trip</b></div><div><span>Fixed fees</span><b>{usd(c.fixed_fee_usd*2)} round trip</b></div></div><Notice>Repeatedly tuning against the test period makes it part of your training process.</Notice><button type="submit" className="button primary full" disabled={disabled}><Play size={17}/>{busy?`Backtesting · ${progress}%`:saving?"Saving configuration…":"Run backtest"}</button><button type="button" className="button full" disabled={busy||saving} onClick={()=>void save()}><Save size={16}/>Save configuration</button><button type="button" className="text-link reset-link" onClick={()=>{const base=strategies.find(s=>s.id==="strategy-demo");if(base){setC({...base.config,wallet_ids:d?.wallets||[]});setStrategyId(undefined);}}}><RotateCcw size={14}/>Reset parameters</button><p className="fine-print">Executed by the shared Python engine. No arbitrary code execution.</p></section></aside></div></form></>;
}
